import type { CrewMember } from './types';

/**
 * Portraits generated by `npm run images` from the photos in dev_crew/ (named after each
 * person, e.g. dev_crew/Varshan.png). They are picked up by id, so adding one needs no
 * change here. A member without a portrait gets their initials on the card instead.
 */
const portraits = import.meta.glob<string>('../assets/crew/*.webp', { eager: true, import: 'default' });
const portraitFor = (id: string): string | undefined => portraits[`../assets/crew/${id}.webp`];

/** Year and department, shown after each name. */
const CLASS = 'III Year – AI&DS';

/**
 * The team who built this site, in card order, as the Dev Crew window shows them (opened
 * from the incognito button in the navigation). `credited` members are also named under
 * "Developed by" in the footer.
 */
export const crew: CrewMember[] = [
  {
    id: 'mohan-prabu-k',
    name: 'Mohan Prabu K',
    role: 'Senior Developer',
    study: CLASS,
    credited: true,
    photo: portraitFor('mohan-prabu-k'),
    links: [
      { kind: 'linkedin', url: 'https://www.linkedin.com/in/mohan-prabu-k-061739325' },
      { kind: 'github', url: 'https://github.com/MohanPrabu018-K' },
      { kind: 'portfolio', url: 'https://portfolio.mohanprabu018.workers.dev/' },
    ],
  },
  {
    id: 'varshan-c',
    name: 'Varshan C',
    role: 'UI/UX Design',
    study: CLASS,
    credited: true,
    photo: portraitFor('varshan-c'),
    links: [
      { kind: 'linkedin', url: 'https://www.linkedin.com/in/varshan-c-56b30a339' },
      { kind: 'github', url: 'https://github.com/Varshanrpsit057' },
    ],
  },
  {
    id: 'barath-s',
    name: 'Barath S',
    role: 'Prompt Engineer & API Authenticator',
    study: CLASS,
    credited: true,
    photo: portraitFor('barath-s'),
    links: [
      { kind: 'linkedin', url: 'https://www.linkedin.com/in/barath-sivalingam-4ba41a330' },
      { kind: 'github', url: 'https://github.com/Barath-S-07' },
    ],
  },
];
